# Tensors in Machine Learning

A **Tensor** is a generalization of **scalars, vectors, and matrices**.  
It can be understood as a **multidimensional array of numbers arranged on a grid**.

Tensors are the **fundamental data structure used in deep learning frameworks** such as:

- TensorFlow
- PyTorch
- Keras

Most operations in machine learning models involve **tensor calculations**.

---

# Understanding Tensors

A tensor is defined as a **collection of numbers arranged along multiple axes (dimensions)**.

Examples:

| Data Type | Tensor Type | Dimensions |
|------|------|------|
| Scalar | 0D Tensor | Single value |
| Vector | 1D Tensor | List of numbers |
| Matrix | 2D Tensor | Table of numbers |
| Higher dimensional arrays | ND Tensor | Multi-dimensional data |

---

# 0D Tensor (Scalar)

A **scalar** is the simplest form of a tensor.

It contains **only a single value** and has **no axes**.

Example:

```
7
```

Properties:

- Dimension: 0
- Shape: ()

Example in Python:

```python
import numpy as np

scalar = np.array(7)
print(scalar)
```

---

# 1D Tensor (Vector)

A **vector** is a **one-dimensional tensor**.

It contains a **list of numbers along a single axis**.

Example:

```
[2, 4, 6, 8]
```

Properties:

- Dimension: 1
- Shape: (4)

Example in Python:

```python
vector = np.array([2,4,6,8])
print(vector)
```

---

# 2D Tensor (Matrix)

A **matrix** is a **two-dimensional tensor**.

It consists of **rows and columns**.

Example:

```
[[1, 2, 3],
 [4, 5, 6]]
```

Properties:

- Dimension: 2
- Shape: (2,3)

Example in Python:

```python
matrix = np.array([[1,2,3],
                   [4,5,6]])
print(matrix)
```

---

# ND Tensor (Higher Dimensional Tensor)

Tensors can extend to **3D, 4D, 5D or even higher dimensions**.

These are called **N-dimensional tensors**.

Example of a **3D Tensor**:

```
[
 [[1,2,3],
  [4,5,6]],

 [[7,8,9],
  [10,11,12]]
]
```

Higher dimensional tensors are used for complex data such as:

- Images
- Videos
- Deep learning models

---

# Rank of a Tensor

The **rank** of a tensor refers to the **number of dimensions (axes)** it has.

Examples:

| Tensor | Rank |
|------|------|
| Scalar | 0 |
| Vector | 1 |
| Matrix | 2 |
| 3D Tensor | 3 |
| 4D Tensor | 4 |

Example:

```
Shape = (3,4,5)
Rank = 3
```

---

# Axes of a Tensor

Axes represent the **directions along which data is organized**.

Example:

Matrix:

```
[[1,2,3],
 [4,5,6]]
```

Axis meanings:

- Axis 0 → rows
- Axis 1 → columns

Understanding axes is important for operations like:

- Summation
- Reshaping
- Broadcasting

---

# Shape of a Tensor

The **shape** of a tensor tells us **how many elements exist along each axis**.

Example:

```
[[1,2,3],
 [4,5,6]]
```

Shape:

```
(2,3)
```

Meaning:

- 2 rows
- 3 columns

---

# Examples of Different Tensor Dimensions

### 1D Tensor Example

```
[10, 20, 30, 40]
```

Shape:

```
(4,)
```

---

### 2D Tensor Example

```
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Shape:

```
(3,3)
```

---

### 3D Tensor Example

Example: RGB Image

```
Height × Width × Channels
```

Shape example:

```
(128, 128, 3)
```

---

### 4D Tensor Example

Used for **deep learning image datasets**.

Example shape:

```
(Number of images, Height, Width, Channels)
```

Example:

```
(32, 128, 128, 3)
```

---

### 5D Tensor Example

Used for **video processing**.

Example shape:

```
(Batch size, Frames, Height, Width, Channels)
```

Example:

```
(16, 30, 128, 128, 3)
```

---

# Why Tensors are Important in Machine Learning

Tensors allow efficient computation on large datasets.

They are used for:

- Neural network computations
- Image processing
- Natural language processing
- Deep learning training

Libraries like **TensorFlow and PyTorch** perform optimized tensor operations using **GPU acceleration**.

---

# Summary

A **Tensor** is a multidimensional array used to represent data in machine learning.

Types of tensors include:

- 0D Tensor → Scalar
- 1D Tensor → Vector
- 2D Tensor → Matrix
- ND Tensor → Higher dimensional data

Understanding tensors is essential for working with **deep learning models and neural networks**.

---

# Tensors in Machine Learning (Beginner → Advanced Guide)

Tensors are the **fundamental data structure used in Machine Learning and Deep Learning**.  
Most ML frameworks such as **TensorFlow and PyTorch** perform computations using tensors.

A **Tensor** is simply a **multi-dimensional array of numbers**.

Examples of tensors include:

| Type | Example | Dimension |
|-----|-----|-----|
| Scalar | 7 | 0D |
| Vector | [1,2,3] | 1D |
| Matrix | [[1,2],[3,4]] | 2D |
| Higher Dimensional Array | Image / Video data | ND |

---

# Level 1 — Beginner Understanding (Basic Tensor Types)

At the beginner level, we focus on understanding:

- Scalars
- Vectors
- Matrices

We will use **NumPy**, which is the foundation for most ML libraries.

Install numpy:

```bash
pip install numpy
```

---

# 0D Tensor (Scalar)

A scalar contains **a single number**.

Example:

```python
import numpy as np

scalar = np.array(10)

print("Scalar Value:", scalar)
print("Shape:", scalar.shape)
print("Dimension:", scalar.ndim)
```

Output:

```
Scalar Value: 10
Shape: ()
Dimension: 0
```

Explanation:

- `shape()` → tells the structure of the tensor
- `ndim` → number of dimensions

---

# 1D Tensor (Vector)

A vector is a **list of numbers arranged in one dimension**.

Example:

```python
vector = np.array([1,2,3,4,5])

print("Vector:", vector)
print("Shape:", vector.shape)
print("Dimension:", vector.ndim)
```

Output:

```
Vector: [1 2 3 4 5]
Shape: (5,)
Dimension: 1
```

Explanation:

- `(5,)` means the tensor contains **5 elements in one dimension**

---

# 2D Tensor (Matrix)

A matrix contains **rows and columns**.

Example:

```python
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print("Matrix:")
print(matrix)

print("Shape:", matrix.shape)
print("Dimension:", matrix.ndim)
```

Output:

```
[[1 2 3]
 [4 5 6]]

Shape: (2,3)
Dimension: 2
```

Explanation:

- `2 rows`
- `3 columns`

---

# Level 2 — Intermediate Tensor Concepts

Now we explore deeper concepts:

- Tensor shape
- Tensor rank
- Tensor operations

---

# Understanding Tensor Rank

Rank = **number of dimensions in the tensor**

Example:

```python
tensor = np.array([
    [1,2,3],
    [4,5,6]
])

print("Rank:", tensor.ndim)
```

Output

```
Rank: 2
```

Explanation:

This tensor has **two axes → rows and columns**.

---

# Tensor Shape

Shape describes **how many elements exist in each axis**.

Example:

```python
tensor = np.array([
    [10,20,30],
    [40,50,60]
])

print("Shape:", tensor.shape)
```

Output

```
(2,3)
```

Meaning:

- 2 rows
- 3 columns

---

# Tensor Operations

Tensors allow mathematical operations.

Example:

```python
a = np.array([1,2,3])
b = np.array([4,5,6])

result = a + b

print("Addition:", result)
```

Output

```
[5 7 9]
```

Explanation:

Each element is **added element-wise**.

---

# Level 3 — Advanced Tensor Examples

Higher dimensional tensors are used in **deep learning applications**.

---

# 3D Tensor Example

Example: Image dataset.

Structure:

```
Height × Width × Channels
```

Example code:

```python
tensor3d = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(tensor3d)
print("Shape:", tensor3d.shape)
print("Dimension:", tensor3d.ndim)
```

Output

```
Shape: (2,2,2)
Dimension: 3
```

Explanation:

- 3 axes exist

---

# 4D Tensor Example (Image Dataset)

Deep learning models process **batches of images**.

Structure:

```
Batch Size × Height × Width × Channels
```

Example:

```python
tensor4d = np.random.rand(10, 28, 28, 3)

print("Shape:", tensor4d.shape)
```

Output

```
(10,28,28,3)
```

Meaning:

- 10 images
- 28 × 28 pixels
- 3 color channels (RGB)

---

# 5D Tensor Example (Video Data)

Video data contains multiple frames.

Structure:

```
Batch × Frames × Height × Width × Channels
```

Example:

```python
tensor5d = np.random.rand(8, 30, 64, 64, 3)

print("Shape:", tensor5d.shape)
```

Output

```
(8,30,64,64,3)
```

Meaning:

- 8 videos
- 30 frames each
- frame size = 64 × 64
- RGB channels

---

# Tensor in Deep Learning Libraries

Modern ML libraries operate on tensors.

Examples:

Libraries using tensors:

- TensorFlow
- PyTorch
- JAX

Example with PyTorch:

```python
import torch

tensor = torch.tensor([[1,2],[3,4]])

print(tensor)
print("Shape:", tensor.shape)
```

---

# Real World Use of Tensors

Tensors are used in:

- Neural Networks
- Image Processing
- Natural Language Processing
- Speech Recognition
- Computer Vision

---

# Summary

Tensor hierarchy:

```
Scalar → Vector → Matrix → Higher Dimensional Tensor
```

Dimensions:

| Tensor | Dimension |
|------|------|
| Scalar | 0D |
| Vector | 1D |
| Matrix | 2D |
| Image Data | 3D |
| Image Dataset | 4D |
| Video Data | 5D |

Understanding tensors is essential for working with **deep learning models and neural networks**.

---